[package]
name = "leptonic"
version = { workspace = true }
edition = "2021"
rust-version = "1.70"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/leptonic"
description = """
The Leptos component library.
"""
categories = ["gui"]
keywords = ["leptos", "components", "component-library"]

[dependencies]
indexmap = "2.0.2"
indoc = "2.0.4"
js-sys = "0.3.64"
leptos = "0.5.1"
leptos-tiptap = "0.4.0"
leptos-use = { version = "0.7.1", features = [
    "math",
] }
leptos_icons = { version = "0.1.0", features = [
    "BsSun",
    "BsMoon",
    "BsCheckCircleFill",
    "BsInfoCircleFill",
    "BsExclamationCircleFill",
    "BsExclamationTriangleFill",
    "BsCaretUp",
    "BsCaretUpFill",
    "BsCaretDown",
    "BsCaretDownFill",
    "BsParagraph",
    "BsTypeBold",
    "BsTypeItalic",
    "BsTypeStrikethrough",
    "BsBlockquoteLeft",
    "BsBrightnessAltHigh",
    "BsTextLeft",
    "BsTextCenter",
    "BsTextRight",
    "BsJustify",
    "BsXCircleFill",
] }
leptos_router = "0.5.1"
serde = "1.0.189"
serde-wasm-bindgen = "0.6.0"
serde_json = "1.0.107"
strum = { version = "0.25.0", features = ["derive"] }
time = { version = "0.3.30", features = [
    "wasm-bindgen",
    "macros",
    "serde",
    "serde-well-known",
] }
tracing = "0.1.39"
uuid = { version = "1.4.1", features = ["v4", "v7", "js", "serde"] }
wasm-bindgen = "0.2.87"
# TODO: What of all below is really required?
web-sys = { version = "0.3.64", features = [
    "DomRect",
    "Event",
    "EventTarget",
    "HtmlFormElement",
    "HtmlInputElement",
    "Storage",
] }

[dev-dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-test = "0.3.37"
web-sys = "0.3.64"

[features]
nightly = ["leptos/nightly", "leptos_router/nightly"]
csr = ["leptos/csr", "leptos_router/csr"]
ssr = ["leptos/ssr", "leptos_router/ssr"]
hydrate = ["leptos/hydrate", "leptos_router/hydrate"]
